var jwt = require('jsonwebtoken');
var uuid4 = require('uuid4');


var customer_id = "600e5b80a4a6804470252623";
var secret = "u9Jl5jHaT_auKVKBP_RgHUonZ97ZBc7Csz3Jso3d5WCDhxXRF_c5oltiUGqypRVWmkkml-XjYIXPU3-vjxiYV-dNeYQPLIEZsVEJyckRc9obHkPWP8d-CyZ3bR1fi1FqiM10rtlbGC4UrHrYKWqT4f_lPs2FGzl0aTUJsriSGgs=";
var app_access_key = "600e5b80a4a6804470252626";
var app_secret = "7dS6uOChutSpifV5PTwhRnvi8tIcE-GyuqT9sHgsCHOew-i93N51GhHOSOmUFOjqeLbjVD1aXVgZ2L8-LkUZeUSayJf7-njIS0eyMcr3NYnSU4gB_Vv0p95sgvAvAe4_UwiTMN4EQgCCFJatofkSM-iYUIh-DeBcYY1QjGe1aB0=";

var payload = {
	    access_key: app_access_key, // App Access Key
	    app_id: "600e5b80a4a6804470252625",     // APP ID
	    room_id: "5f342ec41aa126542cdas3h4", // Room ID generated by createRoom API
		  user_id: "5fc62c5872909272bf9995e1",   // User ID assigned by you (different from 100ms' assigned id)
		  role: "host" //host, teacher, guest, student
};


jwt.sign(payload, app_secret, { algorithm: 'HS256', expiresIn: '24h', issuer: customer_id, jwtid: uuid4()},function(err, token) {
	    console.log(token);
});

